[[headers]]
for = "/*"
  [headers.values]
  Content-Security-Policy = "default-src 'none'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'none'; font-src 'none'; object-src 'none'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'; upgrade-insecure-requests; require-trusted-types-for 'script'"
  Referrer-Policy = "no-referrer"
  X-Content-Type-Options = "nosniff"
  Permissions-Policy = "camera=(), microphone=(), geolocation=()"
